### ISSUE TITLE
[Blue Note]: Archive template

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#10]
![Archive](https://user-images.githubusercontent.com/3593343/219084021-70d04013-b908-489b-8211-4c24692e48da.jpg)

**Comment by vaibhavagar** [comment]
I can work on this

**Comment by MaggieCabrera** [comment]
I assigned you to it and added you to the repo

**Comment by vaibhavagar** [comment]
Thanks, pushed the fix to "feat/archive" branch

**Comment by MaggieCabrera** [comment]
@vaibhavagar I don't see commits on that branch, are you sure you pushed them?

**Comment by MaggieCabrera** [comment]
Nevermind, I see work was done on https://github.com/WordPress/community-themes/pull/44/files

**Comment by MaggieCabrera** [comment]
Let's make sure the changes to index.html are also applied to this template
