### ISSUE TITLE
Blue Note: Announcement post

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#100]
Blue Note was submitted and got approved in the directory and it will soon be up for everyone to download. We should make an announcement post similar to [the one we made for Stacks'](https://make.wordpress.org/themes/2023/05/04/stacks-the-first-community-theme/) launch. Is anyone interested in drafting it? /cc @carolinan @kafleg @scruffian

**Comment by kafleg** [comment]
I'm going to draft it now.

**Comment by MaggieCabrera** [comment]
> I'm going to draft it now.

Thank you so much!
