### ISSUE TITLE
[Blue Note]: Search template

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#11]
![Search](https://user-images.githubusercontent.com/3593343/219084141-a8702491-cf9f-4bb8-8b70-0a3184d67e63.jpg)

**Comment by MaggieCabrera** [comment]
To do:

- [ ] Search results are not centered
- [ ] Search results need to be styled like the design. We can probably use a pattern for this, since the archive template uses a similar style
- [ ] Search input could use the same CSS that is applied to the 404 form input, just needs adding the search template specific classes
- [ ] Match the spacing between the heading and the header
- [ ] Match the heading typography settings to the design
- [ ] The pagination could go without the numbers
- [ ] Let's limit the loop to 3 posts

**Comment by getdave** [comment]
I'll take a look at these.

I'll update as I go...

>  Search results are not centered

✅ These seem to be centered to me.

> Search results need to be styled like the design. We can probably use a pattern for this, since the archive template uses a similar style

✅ Already using `<!-- wp:pattern {"slug":"blue-note/posts"} /-->`.

> Search input could use the same CSS that is applied to the 404 form input, just needs adding the search template specific classes

Let's address this via https://github.com/WordPress/community-themes/pull/71

> Match the spacing between the heading and the header

Let's try https://github.com/WordPress/community-themes/pull/73

> Match the heading typography settings to the design

✅ Seems ok to me.

> The pagination could go without the numbers

✅ Already fixed

> Let's limit the loop to 3 posts

The loop inherits from the Template query. As that comes from Site Settings we can't control that unless we use a custom query loop setting here. Is that what we want @MaggieCabrera?
