### ISSUE TITLE
[Blue Note]: 404 template

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#12]
![404](https://user-images.githubusercontent.com/3593343/219084224-bcb1142c-6a82-4dfb-b24b-9ed9b80c18da.jpg)

**Comment by kimclowa8c** [comment]
I'll work on the 404.

**Comment by kimclow** [comment]
I'll work on the 404.

**Comment by kimclow** [comment]
I had to add some custom CSS to drop the background colour of the search bar: 

`.wp-block-search .wp-block-search__input {
	background: transparent;
}`

**Comment by MaggieCabrera** [comment]
ah, that's a good one, we'll have to also open a Gutenberg PR so that there are controls in the future to change this, but in the meantime using CSS is fine for this

**Comment by kimclow** [comment]
Update on this issue: 
I have got everything to match Figma (I think) except for the opacity of the word "search...". 

I am going to circle back to this in an hour or so after a break.

**Comment by MaggieCabrera** [comment]
It would be awesome if you could open a PR with what you have, even if it's not all done. I think we can go without the opacity change in this case.

**Comment by kimclow** [comment]
Updated custom CSS used for this: 


.wp-block-search .wp-block-search__input {
	background: transparent;
	height: 77px;
	padding-left: 25px;
	padding-top: 22px;
	padding-bottom: 22px;
}

**Comment by kimclow** [comment]
@MaggieCabrera  - I don't actually know how to create a PR. I'll confirm once I've figured it out and submitted it :)

**Comment by MaggieCabrera** [comment]
> @MaggieCabrera - I don't actually know how to create a PR. I'll confirm once I've figured it out and submitted it :)

Feel free to ask me or @carolinan for support!

**Comment by kimclow** [comment]
Hey @MaggieCabrera 
I've submitted the PR. Sorry for the delay.

**Comment by kimclow** [comment]
Exciting! Thank you doing the parts on this I didn't know or understand @MaggieCabrera

**Comment by MaggieCabrera** [comment]
To do:

- [ ] Match the spacing between header and heading and heading and input to the design
- [ ] The typography settings for the heading are not like the design
- [ ] The input is wide width, it should be content width instead
- [ ] Add min-height to the group containing the form so we push the footer down with it

**Comment by getdave** [comment]
> To do:
> 
> * [ ]  Match the spacing between header and heading and heading and input to the design
> * [ ]  The typography settings for the heading are not like the design
> * [ ]  The input is wide width, it should be content width instead
> * [ ]  Add min-height to the group containing the form so we push the footer down with it

Going to take a look at these tasks now
