### ISSUE TITLE
Poetry: credits file

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#133]
We need to create a credits file (like blue note has) and add @ederrengifo to it plus all future contributors (and me I guess)

**Comment by MaggieCabrera** [comment]
let's add 
@shail-mehta 
@samtoohey93
@thetwopct 
@sandroschutt

**Comment by anjadeubzer** [comment]
#wceu-contribution-day - I will have a look at this ticket if I can help as a first time contributor.

**Comment by juanmaguitar** [comment]
@MaggieCabrera @anjadeubzer should this issue be closed as per https://github.com/WordPress/community-themes/pull/207 ?

**Comment by MaggieCabrera** [comment]
> @MaggieCabrera @anjadeubzer should this issue be closed as per #207 ?

yes, thank you
