### ISSUE TITLE
Poetry: header not working

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#138]
The header of the theme is not showing up

**Comment by sandroschutt** [comment]
Could you give us a little more detail on this issue? The header template exists and works, it just doesn't look like a regular header. See the screeshot bellow.

![poetry-header](https://github.com/WordPress/community-themes/assets/68920430/dacbd53c-b6e0-4b10-877d-0a542d6a94f2)

**Comment by thetwopct** [comment]
I could reproduce this when I cloned the community-themes directory in to my themes folder

```
/themes/community-themes/poetry/
```

but cloning directly in themes the header and footer worked

```
/themes/poetry/
```

**Comment by iamsam2e** [comment]
This is resolved with comment on Single page template issue #142 - resolution is removal of the theme slug
