### ISSUE TITLE
Tardis: check wether the name is a registred trademark

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#168]
Let's investigate if we need to rename it or if we can use the name

**Comment by karmatosed** [comment]
Happy to change it if not - let's group think so other options too.

**Comment by karmatosed** [comment]
@MaggieCabrera it is protected.. so my suggestion of Chronology which unless I am mistaken seems free.

**Comment by karmatosed** [comment]
Actually going with Archivist, there was an older theme for Chronology. https://themes.trac.wordpress.org/search?q=archivist&noquickjump=1&changeset=on&ticket=on.
