### ISSUE TITLE
Add TT1 blocks

### ISSUE THREAD

**Issue by carolinan** [WordPress/community-themes#17]
I propose adding TT1 Blocks to this repository. I would like to see it updated.
https://wordpress.org/themes/tt1-blocks/

**Comment by MaggieCabrera** [comment]
Yeah, I think we could have TT1 blocks here, it was the first community theme if we think about it (since it was the first built that wasn't a default one). I believe we had an active PR on the repo to update it, if we bring the theme we should recreate that PR

**Comment by carolinan** [comment]
Yeah, I am not sure of how much of that PR that is already outdated.
