### ISSUE TITLE
View Theme Version Details

### ISSUE THREAD

**Issue by vayurobins** [WordPress/community-themes#190]
Hi. I find it extremely poor user experience how the link to theme version details leads to the general theme page. I don't feel it very relevant to the version details. When there is an update to a theme, the first thing I would like to know about the update, is the changes made. So when there is an update and there is supplied a link to the version details, I would expect to be taken to the exact change log for that version update. I have attached screendumps that hopefully explains what I mean.
![Screenshot 2024-05-31 at 09 55 02](https://github.com/WordPress/community-themes/assets/1386354/a7dc6f05-c5aa-4d1a-bcbd-a035bcc69479)
![Screenshot 2024-05-31 at 09 54 22](https://github.com/WordPress/community-themes/assets/1386354/441a3f7b-6630-4110-b00b-39c93b6905d0)
![Screenshot 2024-05-31 at 10 00 37](https://github.com/WordPress/community-themes/assets/1386354/00f55d45-7e68-4347-82bb-865a3c409def)
![Screenshot 2024-05-31 at 09 58 07](https://github.com/WordPress/community-themes/assets/1386354/33e03a09-7244-4d59-8bb8-14a3fbdee116)
When I click my way through the Development log and find the right Revision and press the View Changes button, the browser cant find it.

So my request for better user experience is when there is an update to a theme, that the link takes me directly to the change log, so I don't have search that info.
Regards Vayu

**Comment by MaggieCabrera** [comment]
Hi! This repo is not in charge of the default themes, you might want to open a [trac ticket](https://core.trac.wordpress.org/) for that
