### ISSUE TITLE
Poetry: change theme colors

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#191]
On theme.json we need to define the body background and text colors as custom presets for the theme, instead of using [the default core preset white color](https://github.com/WordPress/community-themes/blob/96fd5c934238c68ebeb2a3f359d98f3dfd64ca81/poetry/theme.json#L125). The reason why is so the user or a theme variation can change the palette colors and the changes will propagate to the whole site.

Let's find out if other blocks in theme.json or the templates need changing to use the theme palette as well

**Comment by anjadeubzer** [comment]
#wceu-contribution-day - I will have a look at this ticket if I can help as a first time contributer.
