### ISSUE TITLE
Playground link does not install Create block theme plugin

### ISSUE THREAD

**Issue by carolinan** [WordPress/community-themes#30]
When I visit this link in the readme,  only Gutenberg is installed.

https://developer.wordpress.org/playground/demo/?step=playground&theme=twentytwentythree&plugin=gutenberg&plugin=create-block-theme.1.3.8.zip&url=/wp-admin/index.php

**Comment by carolinan** [comment]
@adamziel Hi, can you help me with the correct path to activate both plugins on the playground? I am hoping to use it during WCEU if possible.
I couldn't find the info in the docs.

**Comment by mikachan** [comment]
This URL seems to work: https://playground.wordpress.net/?theme=twentytwentythree&plugin=gutenberg&plugin=create-block-theme.1.8.2.zip&url=/wp-admin/index.php

We should update the link in the readme.

@adamziel, it would be great if you could confirm which URL is correct!

**Comment by adamziel** [comment]
This url should install the latest plugin without hardcoding a version number:

https://playground.wordpress.net/?theme=twentytwentythree&plugin=gutenberg&plugin=create-block-theme

> I couldn't find the info in the docs

Sorry about that! Docs are incomplete to say the least, I hope to get them up to date in the near future.

> I am hoping to use it during WCEU if possible.

Nice! Are you going to give a talk?
