### ISSUE TITLE
Stacks - submission tasks

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#31]
- Update screenshot
- Readme credits for fonts
- Update the color for links on the darker stacks

**Comment by MaggieCabrera** [comment]
@scruffian am I missing something?

**Comment by scruffian** [comment]
- remove the image credit
- revisit the borders on the group blocks cc @SaxonF 
- fix link color on "Proudly powered by WordPress"

**Comment by scruffian** [comment]
I looked at this today:

> Update screenshot
This is not necessary:
<img width="433" alt="Screenshot 2023-04-20 at 15 54 46" src="https://user-images.githubusercontent.com/275961/233405009-74aa85ab-f247-4600-9802-f0938e02f207.png">

> Readme credits for fonts:
We are using system fonts so I don't think we need this.

> Update the color for links on the darker stacks
This is done already.

> remove the image credit
Done in https://github.com/WordPress/community-themes/pull/32

> revisit the borders on the group blocks cc @SaxonF
Let's leave this as is
