### ISSUE TITLE
[Blue Note]: Design for a new theme

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#4]
<img width="1458" alt="Screenshot 2023-02-15 at 09 50 04" src="https://user-images.githubusercontent.com/3593343/218978988-69e3735a-c653-4a27-b2d8-c21b37983dab.png">

https://www.figma.com/community/file/1207273645711252975

Beautiful theme designed by Bea Fialho. Some of the elements on the design might not be achievable without Gutenberg changes. Let's open up issues in the GB repo when those come up so we can work on them too!

**Comment by carolinan** [comment]
What is shown under By Topic? Categories with images? Or 3 posts from one category?

**Comment by MaggieCabrera** [comment]
> What is shown under By Topic? Categories with images? Or 3 posts from one category?

I think those are categories with images, @beafialho can you confirm?

**Comment by beafialho** [comment]
Yes, those would be categories with images.

**Comment by MaggieCabrera** [comment]
The theme has been submitted to the repo: https://themes.trac.wordpress.org/ticket/147323

will close this issue when it's approved
