### ISSUE TITLE
Blue note: credit to contributors

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#46]
Let's make sure to update the theme with a [CREDITS.md](https://github.com/WordPress/community-themes/blob/trunk/stacks/CREDITS.md) file that include everyone that worked on this theme.

**Comment by kafleg** [comment]
Reviewing themes after submitting on WordPress.org also includes? ;)

**Comment by MaggieCabrera** [comment]
What we've done so far is include code, design and pr reviews to count as contribution. The problem with the theme review queue is that it happens after the theme is "finished", but we can always patch the theme to include the reviewers from the team too :D
