### ISSUE TITLE
[Blue Note]: Home template

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#5]
**Desktop:**

![Home (or Front Page)](https://user-images.githubusercontent.com/3593343/219079212-70718225-8ee4-4c37-b78c-5a2a238fd225.jpg)

**Mobile**

![Homepage - Mobile](https://user-images.githubusercontent.com/3593343/219079349-ae2ac68b-2ac3-4c75-aea9-d10c69c87376.jpg)

**Comment by beafialho** [comment]
@MaggieCabrera one alternative for the current lack of option to display categories with images, is to just remove that "By Topic" section and leave only the posts.

**Comment by MaggieCabrera** [comment]
> @MaggieCabrera one alternative for the current lack of option to display categories with images, is to just remove that "By Topic" section and leave only the posts.

Yes, that's an idea. I would like to explore the possibility of adding the functionality in the editor, since it's a common pattern for themes, but if it's a blocker, we can totally remove it. Thanks!

**Comment by beafialho** [comment]
Cool, whatever you think is best works for me, I was only leaving that option on the table 👍🏼

**Comment by carolinan** [comment]
Where does the button "see posts" lead to?

**Comment by MaggieCabrera** [comment]
> Where does the button "see posts" lead to?

Let's go with the archive page

**Comment by Mooore** [comment]
I'll try this :)

**Comment by MaggieCabrera** [comment]
I added you to the repo!

**Comment by MaggieCabrera** [comment]
I remember someone working on this one, but I don't see any changes to the code. Do you have a zip for this, @carolinan?

**Comment by MaggieCabrera** [comment]
I found it! After https://github.com/WordPress/community-themes/pull/61 is merged, what's left to do here is:

- [ ] Add duotone to the images
- [ ] Improve spacing between the query loop and the hero section
- [ ] Remove underline from post titles
- [ ] Font sizes are not correct
- [ ] Reduce line height from post titles
- [ ] Improve spacing between posts vertically
- [ ] The line height on the footer is also too big
- [ ] The social menu should be aligned vertically to the text on the left

**Comment by carolinan** [comment]
> > Where does the button "see posts" lead to?
> 
> Let's go with the archive page

So `page/2/` ?

**Comment by carolinan** [comment]
If we could customize the query pagination text like we can with the post navigation link text, that would solve this problem.
