### ISSUE TITLE
Blue note post editor padding missing

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#66]
This is what I see when I go into the post editor:

<img width="1406" alt="Screenshot 2023-07-24 at 12 28 22" src="https://github.com/WordPress/community-themes/assets/3593343/30cc3112-0a6e-45d1-ae39-e8427a9b20c1">

**Comment by carolinan** [comment]
yeah same...

**Comment by getdave** [comment]
Is that a Editor bug or misconfigured Theme JSON?

**Comment by scruffian** [comment]
I think it's a problem with the template

**Comment by MaggieCabrera** [comment]
this is the post editor, though!

**Comment by scruffian** [comment]
Fixed here: https://github.com/WordPress/community-themes/pull/75
