### ISSUE TITLE
[Blue Note]: Page template

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#8]
**Desktop:**

![Page](https://user-images.githubusercontent.com/3593343/219083577-4a6262dc-0534-4094-a971-dd9ad66c9eed.jpg)

**Mobile:**
![Page - Mobile](https://user-images.githubusercontent.com/3593343/219083586-5a492bcf-90fd-48ae-885c-4869edd70da5.jpg)

**Comment by markus9312** [comment]
Markus & Humera

**Comment by MaggieCabrera** [comment]
> Markus & Humera

are you going to work on this one? @markus9312

**Comment by msmaniya1** [comment]
Yes, me and @markus9312 are working on it. We evaluated that medium should be 22px.

**Comment by markus9312** [comment]
Large should be 40px
X-large should be 80px

**Comment by MaggieCabrera** [comment]
I added you both to the repo!

**Comment by markus9312** [comment]
Github issues :-)

{
  "$schema": "https://schemas.wp.org/wp/6.2/theme.json",
  "customTemplates": [
    {
      "name": "single-no-sidebar",
      "postTypes": ["page", "post"],
      "title": "Single, no sidebar"
    }
  ],
  "settings": {
    "appearanceTools": true,
    "color": {
      "palette": [
        {
          "slug": "base",
          "name": "Base",
          "color": "#F5F3EA"
        },
        {
          "slug": "contrast",
          "name": "Contrast",
          "color": "#000000"
        },
        {
          "slug": "primary",
          "name": "Primary",
          "color": "#6E6E6E"
        },
        {
          "slug": "secondary",
          "name": "Secondary",
          "color": "#ADADAD"
        }
      ],
      "duotone": [
        {
          "slug": "black-pink",
          "name": "Black and pink",
          "colors": ["#000000", "#C8266A"]
        },
        {
          "slug": "black-blue",
          "name": "Black and blue",
          "colors": ["#000000", "#3371BD"]
        },
        {
          "slug": "black-green",
          "name": "Black and green",
          "colors": ["#000000", "#92A317"]
        },
        {
          "slug": "black-yellow",
          "name": "Black and yellow",
          "colors": ["#000000", "#FCE9A5"]
        },
        {
          "slug": "black-orange",
          "name": "Black and orange",
          "colors": ["#000000", "#EA5200"]
        },
        {
          "slug": "black-purple",
          "name": "Black and purple",
          "colors": ["#000000", "#6C4A8F"]
        },
        {
          "slug": "black-white",
          "name": "Black and white",
          "colors": ["#000000", "#FFFFFF"]
        }
      ]
    },
    "layout": {
      "contentSize": "874px",
      "wideSize": "1300px"
    },
    "spacing": {
      "units": ["%", "px", "em", "rem", "vh", "vw"]
    },
    "typography": {
      "fluid": true,
      "fontFamilies": [
        {
          "fontFamily": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif",
          "name": "System Font",
          "slug": "system-font"
        },
        {
          "fontFamily": "Old Standard TT",
          "slug": "old-standard-tt",
          "fontFace": [
            {
              "fontFamily": "Old Standard TT",
              "fontStyle": "normal",
              "fontWeight": "400",
              "src": [
                "file:./assets/fonts/old-standard-tt-v18-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-regular.woff2"
              ]
            },
            {
              "fontFamily": "Old Standard TT",
              "fontStyle": "italic",
              "fontWeight": "400",
              "src": [
                "file:./assets/fonts/old-standard-tt-v18-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-italic.woff2"
              ]
            },
            {
              "fontFamily": "Old Standard TT",
              "fontStyle": "normal",
              "fontWeight": "700",
              "src": [
                "file:./assets/fonts/old-standard-tt-v18-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-700.woff2"
              ]
            }
          ]
        }
      ],
      "fontSizes": [
        {
          "fluid": {
            "min": "0.875rem",
            "max": "1rem"
          },
          "size": "1rem",
          "slug": "small"
        },
        {
          "fluid": {
            "min": "1.188rem",
            "max": "1.375rem"
          },
          "size": "1.375rem",
          "slug": "medium"
        },
        {
          "fluid": {
            "min": "2.125rem",
            "max": "2.5rem"
          },
          "size": "2.5rem",
          "slug": "large"
        },
        {
          "fluid": {
            "min": "4.125rem",
            "max": "5rem"
          },
          "size": "5rem",
          "slug": "x-large"
        },
        {
          "fluid": {
            "min": "4rem",
            "max": "10rem"
          },
          "size": "10rem",
          "slug": "xx-large"
        }
      ]
    },
    "useRootPaddingAwareAlignments": true
  },
  "styles": {
    "blocks": {
      "core/site-title": {
        "elements": {
          "link": {
            "typography": {
              "textDecoration": "none"
            }
          }
        },
        "typography": {
          "fontSize": "var(--wp--preset--font-size--medium)"
        }
      },
      "core/post-title": {
        "typography": {
          "fontSize": "var(--wp--preset--font-size--x-large)"
        }
      },
      "core/post-content": {
        "typography": {
          "fontSize": "var(--wp--preset--font-size--medium)",
          "lineHeight": "1.6"
        }
      },
      "core/image": {
        "spacing": {
          "margin": {
            "top": "6.25rem!important",
            "bottom": "6.25rem!important"
          }
        }
      }
    },
    "color": {
      "background": "var(--wp--preset--color--base)",
      "text": "var(--wp--preset--color--contrast)"
    },
    "elements": {
      "button": {
        "border": {
          "radius": "0"
        }
      },
      "heading": {
        "typography": {
          "letterSpacing": "-1px"
        }
      }
    },
    "spacing": {
      "padding": {
        "top": "0",
        "right": "var(--wp--preset--spacing--60)",
        "bottom": "0",
        "left": "var(--wp--preset--spacing--60)"
      }
    },
    "typography": {
      "fontFamily": "var(--wp--preset--font-family--old-standard-tt)",
      "fontSize": ""
    }
  },

  "templateParts": [
    {
      "area": "header",
      "name": "header",
      "title": "Header"
    },
    {
      "area": "header",
      "name": "header-large",
      "title": "Large Header"
    },
    {
      "area": "footer",
      "name": "footer",
      "title": "Footer"
    },
    {
      "area": "footer",
      "name": "footer-large",
      "title": "Large footer"
    }
  ],

  "version": 2
}

**Comment by markus9312** [comment]
Github issues :-) Please delete this comment so people from the future don't laugh at me LOL

```json
{
  "$schema": "https://schemas.wp.org/wp/6.2/theme.json",
  "customTemplates": [
    {
      "name": "single-no-sidebar",
      "postTypes": ["page", "post"],
      "title": "Single, no sidebar"
    }
  ],
  "settings": {
    "appearanceTools": true,
    "color": {
      "palette": [
        {
          "slug": "base",
          "name": "Base",
          "color": "#F5F3EA"
        },
        {
          "slug": "contrast",
          "name": "Contrast",
          "color": "#000000"
        },
        {
          "slug": "primary",
          "name": "Primary",
          "color": "#6E6E6E"
        },
        {
          "slug": "secondary",
          "name": "Secondary",
          "color": "#ADADAD"
        }
      ],
      "duotone": [
        {
          "slug": "black-pink",
          "name": "Black and pink",
          "colors": ["#000000", "#C8266A"]
        },
        {
          "slug": "black-blue",
          "name": "Black and blue",
          "colors": ["#000000", "#3371BD"]
        },
        {
          "slug": "black-green",
          "name": "Black and green",
          "colors": ["#000000", "#92A317"]
        },
        {
          "slug": "black-yellow",
          "name": "Black and yellow",
          "colors": ["#000000", "#FCE9A5"]
        },
        {
          "slug": "black-orange",
          "name": "Black and orange",
          "colors": ["#000000", "#EA5200"]
        },
        {
          "slug": "black-purple",
          "name": "Black and purple",
          "colors": ["#000000", "#6C4A8F"]
        },
        {
          "slug": "black-white",
          "name": "Black and white",
          "colors": ["#000000", "#FFFFFF"]
        }
      ]
    },
    "layout": {
      "contentSize": "874px",
      "wideSize": "1300px"
    },
    "spacing": {
      "units": ["%", "px", "em", "rem", "vh", "vw"]
    },
    "typography": {
      "fluid": true,
      "fontFamilies": [
        {
          "fontFamily": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif",
          "name": "System Font",
          "slug": "system-font"
        },
        {
          "fontFamily": "Old Standard TT",
          "slug": "old-standard-tt",
          "fontFace": [
            {
              "fontFamily": "Old Standard TT",
              "fontStyle": "normal",
              "fontWeight": "400",
              "src": [
                "file:./assets/fonts/old-standard-tt-v18-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-regular.woff2"
              ]
            },
            {
              "fontFamily": "Old Standard TT",
              "fontStyle": "italic",
              "fontWeight": "400",
              "src": [
                "file:./assets/fonts/old-standard-tt-v18-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-italic.woff2"
              ]
            },
            {
              "fontFamily": "Old Standard TT",
              "fontStyle": "normal",
              "fontWeight": "700",
              "src": [
                "file:./assets/fonts/old-standard-tt-v18-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-700.woff2"
              ]
            }
          ]
        }
      ],
      "fontSizes": [
        {
          "fluid": {
            "min": "0.875rem",
            "max": "1rem"
          },
          "size": "1rem",
          "slug": "small"
        },
        {
          "fluid": {
            "min": "1.188rem",
            "max": "1.375rem"
          },
          "size": "1.375rem",
          "slug": "medium"
        },
        {
          "fluid": {
            "min": "2.125rem",
            "max": "2.5rem"
          },
          "size": "2.5rem",
          "slug": "large"
        },
        {
          "fluid": {
            "min": "4.125rem",
            "max": "5rem"
          },
          "size": "5rem",
          "slug": "x-large"
        },
        {
          "fluid": {
            "min": "4rem",
            "max": "10rem"
          },
          "size": "10rem",
          "slug": "xx-large"
        }
      ]
    },
    "useRootPaddingAwareAlignments": true
  },
  "styles": {
    "blocks": {
      "core/site-title": {
        "elements": {
          "link": {
            "typography": {
              "textDecoration": "none"
            }
          }
        },
        "typography": {
          "fontSize": "var(--wp--preset--font-size--medium)"
        }
      },
      "core/post-title": {
        "typography": {
          "fontSize": "var(--wp--preset--font-size--x-large)"
        }
      },
      "core/post-content": {
        "typography": {
          "fontSize": "var(--wp--preset--font-size--medium)",
          "lineHeight": "1.6"
        }
      },
      "core/image": {
        "spacing": {
          "margin": {
            "top": "6.25rem!important",
            "bottom": "6.25rem!important"
          }
        }
      }
    },
    "color": {
      "background": "var(--wp--preset--color--base)",
      "text": "var(--wp--preset--color--contrast)"
    },
    "elements": {
      "button": {
        "border": {
          "radius": "0"
        }
      },
      "heading": {
        "typography": {
          "letterSpacing": "-1px"
        }
      }
    },
    "spacing": {
      "padding": {
        "top": "0",
        "right": "var(--wp--preset--spacing--60)",
        "bottom": "0",
        "left": "var(--wp--preset--spacing--60)"
      }
    },
    "typography": {
      "fontFamily": "var(--wp--preset--font-family--old-standard-tt)",
      "fontSize": ""
    }
  },

  "templateParts": [
    {
      "area": "header",
      "name": "header",
      "title": "Header"
    },
    {
      "area": "header",
      "name": "header-large",
      "title": "Large Header"
    },
    {
      "area": "footer",
      "name": "footer",
      "title": "Footer"
    },
    {
      "area": "footer",
      "name": "footer-large",
      "title": "Large footer"
    }
  ],

  "version": 2
}
```

**Comment by markus9312** [comment]
`{
  "$schema": "https://schemas.wp.org/wp/6.2/theme.json",
  "customTemplates": [
    {
      "name": "single-no-sidebar",
      "postTypes": ["page", "post"],
      "title": "Single, no sidebar"
    }
  ],
  "settings": {
    "appearanceTools": true,
    "color": {
      "palette": [
        {
          "slug": "base",
          "name": "Base",
          "color": "#F5F3EA"
        },
        {
          "slug": "contrast",
          "name": "Contrast",
          "color": "#000000"
        },
        {
          "slug": "primary",
          "name": "Primary",
          "color": "#6E6E6E"
        },
        {
          "slug": "secondary",
          "name": "Secondary",
          "color": "#ADADAD"
        }
      ],
      "duotone": [
        {
          "slug": "black-pink",
          "name": "Black and pink",
          "colors": ["#000000", "#C8266A"]
        },
        {
          "slug": "black-blue",
          "name": "Black and blue",
          "colors": ["#000000", "#3371BD"]
        },
        {
          "slug": "black-green",
          "name": "Black and green",
          "colors": ["#000000", "#92A317"]
        },
        {
          "slug": "black-yellow",
          "name": "Black and yellow",
          "colors": ["#000000", "#FCE9A5"]
        },
        {
          "slug": "black-orange",
          "name": "Black and orange",
          "colors": ["#000000", "#EA5200"]
        },
        {
          "slug": "black-purple",
          "name": "Black and purple",
          "colors": ["#000000", "#6C4A8F"]
        },
        {
          "slug": "black-white",
          "name": "Black and white",
          "colors": ["#000000", "#FFFFFF"]
        }
      ]
    },
    "layout": {
      "contentSize": "874px",
      "wideSize": "1300px"
    },
    "spacing": {
      "units": ["%", "px", "em", "rem", "vh", "vw"]
    },
    "typography": {
      "fluid": true,
      "fontFamilies": [
        {
          "fontFamily": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif",
          "name": "System Font",
          "slug": "system-font"
        },
        {
          "fontFamily": "Old Standard TT",
          "slug": "old-standard-tt",
          "fontFace": [
            {
              "fontFamily": "Old Standard TT",
              "fontStyle": "normal",
              "fontWeight": "400",
              "src": [
                "file:./assets/fonts/old-standard-tt-v18-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-regular.woff2"
              ]
            },
            {
              "fontFamily": "Old Standard TT",
              "fontStyle": "italic",
              "fontWeight": "400",
              "src": [
                "file:./assets/fonts/old-standard-tt-v18-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-italic.woff2"
              ]
            },
            {
              "fontFamily": "Old Standard TT",
              "fontStyle": "normal",
              "fontWeight": "700",
              "src": [
                "file:./assets/fonts/old-standard-tt-v18-cyrillic_cyrillic-ext_latin_latin-ext_vietnamese-700.woff2"
              ]
            }
          ]
        }
      ],
      "fontSizes": [
        {
          "fluid": {
            "min": "0.875rem",
            "max": "1rem"
          },
          "size": "1rem",
          "slug": "small"
        },
        {
          "fluid": {
            "min": "1.188rem",
            "max": "1.375rem"
          },
          "size": "1.375rem",
          "slug": "medium"
        },
        {
          "fluid": {
            "min": "2.125rem",
            "max": "2.5rem"
          },
          "size": "2.5rem",
          "slug": "large"
        },
        {
          "fluid": {
            "min": "4.125rem",
            "max": "5rem"
          },
          "size": "5rem",
          "slug": "x-large"
        },
        {
          "fluid": {
            "min": "4rem",
            "max": "10rem"
          },
          "size": "10rem",
          "slug": "xx-large"
        }
      ]
    },
    "useRootPaddingAwareAlignments": true
  },
  "styles": {
    "blocks": {
      "core/site-title": {
        "elements": {
          "link": {
            "typography": {
              "textDecoration": "none"
            }
          }
        },
        "typography": {
          "fontSize": "var(--wp--preset--font-size--medium)"
        }
      },
      "core/post-title": {
        "typography": {
          "fontSize": "var(--wp--preset--font-size--x-large)"
        }
      },
      "core/post-content": {
        "typography": {
          "fontSize": "var(--wp--preset--font-size--medium)",
          "lineHeight": "1.6"
        }
      },
      "core/image": {
        "spacing": {
          "margin": {
            "top": "6.25rem!important",
            "bottom": "6.25rem!important"
          }
        }
      }
    },
    "color": {
      "background": "var(--wp--preset--color--base)",
      "text": "var(--wp--preset--color--contrast)"
    },
    "elements": {
      "button": {
        "border": {
          "radius": "0"
        }
      },
      "heading": {
        "typography": {
          "letterSpacing": "-1px"
        }
      }
    },
    "spacing": {
      "padding": {
        "top": "0",
        "right": "var(--wp--preset--spacing--60)",
        "bottom": "0",
        "left": "var(--wp--preset--spacing--60)"
      }
    },
    "typography": {
      "fontFamily": "var(--wp--preset--font-family--old-standard-tt)",
      "fontSize": ""
    }
  },

  "templateParts": [
    {
      "area": "header",
      "name": "header",
      "title": "Header"
    },
    {
      "area": "header",
      "name": "header-large",
      "title": "Large Header"
    },
    {
      "area": "footer",
      "name": "footer",
      "title": "Footer"
    },
    {
      "area": "footer",
      "name": "footer-large",
      "title": "Large footer"
    }
  ],

  "version": 2
}`

**Comment by MaggieCabrera** [comment]
I think this one is missing work on the template

**Comment by MaggieCabrera** [comment]
To do:

- [ ] Spacing and typography to match the design
- [ ] Main column is too wide
