### ISSUE TITLE
Blue note: Launch tasks

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#89]
There are a few issues that still need to be looked into:

- https://github.com/WordPress/community-themes/issues/78 (I don't feel we need to add all the patterns, but there are still a few that I think merit being included before launch)
- https://github.com/WordPress/community-themes/issues/11 has a patch ready
- https://github.com/WordPress/community-themes/issues/8 it's minor but should be easy to fix

Besides that we need to:

- [x] Add credit to the people that worked on the theme lately (@getdave, @jeryj and @ajlende I believe)
- [x] Add credit for the images we added
- [x] The theme check plugin only shows one warning:
> WARNING: Found a translation function that is missing a text-domain in the file patterns/hidden-404.php. Function esc_html_e, with the arguments 'Search the site'. 
- [x] Check that the theme tags are accurate
- [x] Add credits for the fonts included in the theme
- [x] Update the version to 1.0.0 and add a changelog entry
- [x] Change contributors on the readme and styles.css file to `wordpressdotorg` and the author URL to be `https://wordpress.org/themes/author/wordpressdotorg/`
- [x] Add a theme description, @beafialho can you help with this?

**Comment by MaggieCabrera** [comment]
Also, let's draft a post for the make blog to be published after the theme is officially launched

**Comment by kafleg** [comment]
I can work on readme and style.css file. Do we need to change tested up to 6.3?

**Comment by MaggieCabrera** [comment]
> I can work on readme and style.css file. Do we need to change tested up to 6.3?

yep, sounds about right. Thank you!

**Comment by kafleg** [comment]
@MaggieCabrera Requires at least: 6.1

This should be 6.1 or 6.2?

**Comment by kafleg** [comment]
@MaggieCabrera Can you provide me the license link of the images used in the theme assets and font license? It need to mention in the readme file.

**Comment by MaggieCabrera** [comment]
@beafialho I don't know where to get the credit info for the images here either

**Comment by MaggieCabrera** [comment]
The only font we are bundling is this one: https://fonts.google.com/specimen/Old+Standard+TT/about

**Comment by kafleg** [comment]
thank you!

**Comment by kafleg** [comment]
> @MaggieCabrera Requires at least: 6.1
> 
> This should be 6.1 or 6.2?

I set it 6.1 because the theme should work with the 2 major prior versions. (this was the guidelines). I can change to another version if you think that it should be changed.

**Comment by MaggieCabrera** [comment]
> I set it 6.1 because the theme should work with the 2 major prior versions. (this was the guidelines). I can change to another version if you think that it should be changed.

That guideline I believe is only for default themes but I think it applies well to this one too, I don't think it will break in 6.1 I believe

**Comment by beafialho** [comment]
Sorry about the delay.

> @beafialho I don't know where to get the credit info for the images here either

Here are the image sources:
- https://en.wikipedia.org/wiki/Ethel_Waters#/media/File:Ethel_Waters_-_William_P._Gottlieb.jpg
- https://en.wikipedia.org/wiki/Cab_Calloway#/media/File:Cab_Calloway_Gottlieb.jpg
- https://commons.wikimedia.org/wiki/File:Thelonious_Monk,_Minton%27s_Playhouse,_New_York,_N.Y.,_ca._Sept._1947_(William_P._Gottlieb_06271).jpg#/media/File:Thelonious_Monk,_Minton's_Playhouse,_New_York,_N.Y.,_ca._Sept._1947_(William_P._Gottlieb_06271).jpg
- https://stocksnap.io/photo/vinyl-music-DPMX3QCLBT
- https://stocksnap.io/photo/books-knowledge-XAZG2TR9PW

> Add a theme description, @beafialho can you help with this?

Sure, here's a description:

`Blue Note is an elegant and fun block theme inspired by jazz and the record label "Blue Note Records". Its timeless typography and modern, responsive layouts are perfect for writers and bloggers.`

**Comment by kafleg** [comment]
Thank you @beafialho 
I'm going to check the link and add the license and description.

**Comment by MaggieCabrera** [comment]
> Thank you @beafialho I'm going to check the link and add the license and description.

I'm doing this right now over at https://github.com/WordPress/community-themes/pull/93 I'll tag you for review
