### ISSUE TITLE
[Blue Note]: Index template

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/community-themes#9]
![Index](https://user-images.githubusercontent.com/3593343/219083827-6c1df364-f65c-49d9-81a1-13991f58d11c.jpg)

**Comment by Matthijs-MO** [comment]
I'll work on this one!

**Comment by MaggieCabrera** [comment]
Do we have a PR or zip for this one?

**Comment by MaggieCabrera** [comment]
To do:

- [ ] Let's work on this one at the same time as the Archive page and make the loop a pattern (the search template can use the same pattern too)
- [ ] Center the content 
- [ ] The width of the content should match the design
- [ ] Typography should match the design
- [ ] Let's match the spacing to the design
- [ ] Add the rotation to the images using the block styles we've created and add the CSS necessary
- [ ] Apply duotone to the featured images
- [ ] Remove the numbers from the pagination
